name: libcamera manual colcon build

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build:
    name: libcamera
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:22.04

    steps:
      - name: install ROS2
        uses: ros-tooling/setup-ros@v0.3

      - name: install colcon-meson
        run: |
          pip install git+https://github.com/colcon/colcon-meson.git@main

      - name: apt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt -y install ninja-build
          apt -y install --no-install-recommends git meson libyaml-dev python3-yaml python3-ply python3-jinja2 libgnutls28-dev openssl libyaml-dev
          apt -y install --no-install-recommends ca-certificates
          apt install --no-install-recommends -y python3-pip
          pip3 install --user --upgrade meson

      - name: build
        run: |
          mkdir -p ~/libcamera_ws/src
          git clone https://git.libcamera.org/libcamera/libcamera.git ~/libcamera_ws/src/libcamera
          cd ~/libcamera_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro rolling
          colcon build --event-handlers=console_direct+ --meson-args --buildtype=release --auto-features=disabled -Dtest=false -Dv4l2=true
