name: libcamera colcon build

on: push

jobs:
  build:
    name: libcamera
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:22.04

    steps:
      - name: fetch source
        uses: actions/checkout@v3

      - name: install ROS2
        uses: ros-tooling/setup-ros@v0.6

      - name: build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: libcamera
          target-ros2-distro: rolling
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "meson-args": ["--buildtype=release", "--auto-features=disabled"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
